export function initializeEllipticCurveParameters() : any;
export function set_ec_params(name: string) : any;
export function set_secp128r1() : any;
export function set_secp160k1() : any;
export function set_secp160r1() : any;
export function set_secp192k1() : any;
export function set_secp192r1() : any;
export function set_secp224r1() : any;
export function set_secp256r1() : any;
export function get_curve() : any;
export function get_G(curve: any) : any;
export function generateSendersPrivateMultiplier(sendersPassword: any, sendersSalt: any) : any;
export function calculateSendersMultipliedPoint(sendersPrivateMultiplier: any) : any;
export function calculateSendersCommonSecretKey() : string;
export function generateReceiversPrivateMultiplier() : string;
export function calculateReceiversMultipliedPoint() : string;
export function calculateReceiversCommonSecretKey() : string;
export function encryptMessage(messagePlainText: string) : string;
export function decryptMessage(messageCipherText: string) : string;
export function pick_rand() : any;
export function getN(n: any) : any;
export function generateRandomString(len: number) : string;
export function convertStringToHex(originalString: string) : string;
