export function initializeEllipticCurveParameters();
export function set_ec_params = function (name: string) : any;
export function set_secp128r1();
export function set_secp160k1();
export function set_secp160r1();
export function set_secp192k1();
export function set_secp192r1();
export function set_secp224r1();
export function set_secp256r1();
export function get_curve();
export function get_G = function (curve: any) : any;
export function generateSendersPrivateMultiplier();
export function calculateSendersMultipliedPoint();
export function calculateSendersCommonSecretKey();
export function generateReceiversPrivateMultiplier();
export function calculateReceiversMultipliedPoint();
export function calculateReceiversCommonSecretKey();
export function encryptMessage();
export function decryptMessage();
export function pick_rand();
export function getN = function (n: any) : any;
export function generateRandomString(len: number) : string;
export function convertStringToHex = function (originalString: string) : string;
