export function bnClone () : any;
export function bnIntValue () : any;
export function bnByteValue () : any;
export function bnShortValue () : any;
export function bnpChunkSize (r: any) : any;
export function bnSigNum () : any;
export function bnpToRadix (b: any) : any;
export function bnpFromRadix (s: any,b: any) : any;
export function bnpFromNumber (a: any,b: any,c: any) : any;
export function bnToByteArray () : any;
export function bnEquals (a: any) : any;
export function bnMin (a: any) : any;
export function bnMax (a: any) : any;
export function bnpBitwiseTo (a: any,op: any,r: any) : any;
export function op_and (x: any,y: any) : any;
export function bnAnd (a: any) : any;
export function op_or (x: any,y: any) : any;
export function bnOr (a: any) : any;
export function op_xor (x: any,y: any) : any;
export function bnXor (a: any) : any;
export function op_andnot (x: any,y: any) : any;
export function bnAndNot (a: any) : any;
export function bnNot () : any;
export function bnShiftLeft (n: any) : any;
export function bnShiftRight (n: any) : any;
export function lbit (x: any) : any;
export function bnGetLowestSetBit () : any;
export function cbit (x: any) : any;
export function bnBitCount () : any;
export function bnTestBit (n: any) : any;
export function bnpChangeBit (n: any,op: any) : any;
export function bnSetBit (n: any) : any;
export function bnClearBit (n: any) : any;
export function bnFlipBit (n: any) : any;
export function bnpAddTo (a: any,r: any) : any;
export function bnAdd (a: any) : any;
export function bnSubtract (a: any) : any;
export function bnMultiply (a: any) : any;
export function bnSquare () : any;
export function bnDivide (a: any) : any;
export function bnRemainder (a: any) : any;
export function bnDivideAndRemainder (a: any) : any;
export function bnpDMultiply (n: any) : any;
export function bnpDAddOffset (n: any,w: any) : any;
export function NullExp () : any;
export function nNop (x: any) : any;
export function nMulTo (x: any,y: any,r: any) : any;
export function nSqrTo (x: any,r: any) : any;
export function bnPow (e: any) : any;
export function bnpMultiplyLowerTo (a: any,n: any,r: any) : any;
export function bnpMultiplyUpperTo (a: any,n: any,r: any) : any;
export function Barrett (m: any) : any;
export function barrettConvert (x: any) : any;
export function barrettRevert (x: any) : any;
export function barrettReduce (x: any) : any;
export function barrettSqrTo (x: any,r: any) : any;
export function barrettMulTo (x: any,y: any,r: any) : any;
export function bnModPow (e: any,m: any) : any;
export function bnGCD (a: any) : any;
export function bnpModInt (n: any) : any;
export function bnModInverse (m: any) : any;
export function bnIsProbablePrime (t: any) : any;
export function bnpMillerRabin (t: any) : any;

