export function ECFieldElementFp(q: any,x: any) : any;
export function feFpEquals(other: any) : any;
export function feFpToBigInteger() : any;
export function feFpNegate() : any;
export function feFpAdd(b: any) : any;
export function feFpSubtract(b: any) : any;
export function feFpMultiply(b: any) : any;
export function feFpSquare() : any;
export function feFpDivide(b: any) : any;
export function ECPointFp(curve: any,x: any,y: any,z: any) : any;
export function pointFpGetX() : any;
export function pointFpGetY() : any;
export function pointFpEquals(other: any) : any;
export function pointFpIsInfinity() : any;
export function pointFpNegate() : any;
export function pointFpAdd(b: any) : any;
export function pointFpTwice() : any;
export function pointFpMultiply(k: any) : any;
export function pointFpMultiplyTwo(j: any,x: any,k: any) : any;
export function ECCurveFp(q: any,a: any,b: any) : any;
export function curveFpGetQ() : any;
export function curveFpGetA() : any;
export function curveFpGetB() : any;
export function curveFpEquals(other: any) : any;
export function curveFpGetInfinity() : any;
export function curveFpFromBigInteger(x: any) : any;
export function curveReduce(x: any) : any;
export function curveFpDecodePointHex(s: any) : any;
export function curveFpEncodePointHex(p: any) : any;
